# Generated by Django 3.0.6 on 2020-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
