# Generated by Django 3.0.6 on 2020-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200530_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postmedia',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
